version: "3.7"
services: 
    webapp1:
        build:
            context: ./web-app
            args:
                PORT: 9998
        ports: 
            - "9998:9998"

    webapp2:
        build:
            context: ./web-app
            args:
                PORT: 9999
        ports: 
            - "9999:9999"
    
    nginx-lab3:
        build: .
        ports: 
            - "8080:8080"